export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const CLEAR_USER = 'CLEAR_USER'